services:
  db:
    image: postgres:16
    ports:
      - ${DB_PORT:-5432}:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-kishax_db}
      TZ: Asia/Tokyo
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres}"]
      interval: 10s
      timeout: 5s
      retries: 5

# app:
#   build:
#     context: .
#     dockerfile: Dockerfile
#     target: development
#     args:
#       NODE_ENV: development
#   ports:
#     - ${APP_PORT:-3000}:3000
#   volumes:
#     - .:/app
#     - /app/node_modules
#     - /app/.next
#   environment:
#     - NODE_ENV=development
#     - DATABASE_URL=postgresql://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-postgres}@db:5432/${POSTGRES_DB:-kishax_db}
#     - NEXTAUTH_URL=http://localhost:${APP_PORT:-3000}
#     - NEXTAUTH_SECRET=${NEXTAUTH_SECRET:-development-secret-key-minimum-32-chars}
#     - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID:-}
#     - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET:-}
#     - DISCORD_CLIENT_ID=${DISCORD_CLIENT_ID:-}
#     - DISCORD_CLIENT_SECRET=${DISCORD_CLIENT_SECRET:-}
#     - TWITTER_CLIENT_ID=${TWITTER_CLIENT_ID:-}
#     - TWITTER_CLIENT_SECRET=${TWITTER_CLIENT_SECRET:-}
#   depends_on:
#     db:
#       condition: service_healthy
#   develop:
#     watch:
#       - action: sync
#         path: ./src
#         target: /app/src
#       - action: sync
#         path: ./public
#         target: /app/public
#       - action: rebuild
#         path: package.json

volumes:
  postgres-data: